module.exports = [
  {
    item_name: "Income",
    amount: 1000,
    date: "2022-01-06",
    from: "Employer",
    category: "Income",
  },
  {
    item_name: "Taxes",
    amount: -500,
    date: "2022-02-01",
    from: "IRS",
    category: "Savings",
  },
  {
    item_name: "Retirement",
    amount: -200,
    date: "2022-03-02",
    from: "Insurance",
    category: "savings",
  },
  {
    item_name: "Income Job2",
    amount: -100,
    date: "2022-04-03",
    from: "Employer",
    category: "Income",
  },
  {
    item_name: "Credit Card Payment",
    amount: -100,
    date: "2022-05-04",
    from: "Bank",
    category: "Savings",
  },
  {
    item_name: "Coffee",
    amount: -4,
    date: "2022-06-01",
    from: "Grocery Store",
    category: "Daily Expenses",
  },
  {
    item_name: "Internet",
    amount: -100,
    date: "2022-06-02",
    from: "ATT",
    category: "Expenses",
  },
  {
    item_name: "Groceries",
    amount: -9.99,
    date: "2022-07-03",
    from: "A1 Supermarket",
    category: "Daily Expenses",
  },
  {
    item_name: "Pet Food",
    amount: -4.50,
    date: "2022-07-10",
    from: "Pet Store",
    category: "Expenses",
  }
]