module.exports = [
  {
    item_name: "Income",
    amount: 1000,
    date: "01/05/2022",
    from: "employer",
    category: "income",
  },
  {
    item_name: "Taxes",
    amount: -500,
    date: "01/06/2022",
    from: "bank",
    category: "bank",
  },
  {
    item_name: "Retirement",
    amount: -200,
    date: "01/07/2022",
    from: "pet store",
    category: "savings",
  },
  {
    item_name: "Savings",
    amount: -100,
    date: "01/08/2022",
    from: "pet store",
    category: "bank",
  },
  {
    item_name: "Credit Card Payment",
    amount: -100,
    date: "01/07/2022",
    from: "pet store",
    category: "savings",
  },
  {
    item_name: "Coffee",
    amount: -4,
    date: "01/08/2022",
    from: "store",
    category: "daily expenses",
  },
  {
    item_name: "Internet",
    amount: -100,
    date: "01/08/2022",
    from: "ATT",
    category: "expenses",
  },
  {
    item_name: "Groceries",
    amount: -76,
    date: "01/20/2022",
    from: "store",
    category: "daily expenses",
  },
  {
    item_name: "Pet Food",
    amount: -7,
    date: "01/22/2022",
    from: "Pet Store",
    category: "Expenses",
  }
]